---
format: html
---

## Ressources et liens externes

### Ressources R

#### [R packages](https://r-pkgs.org/){target="_blank"}

Livre de référence sur ce qu'est un package, comment doit être structuré un package, les bonnes pratiques de développement, de nommage, les conventions et des outils pratiques pour tout développeur R.

#### [R for Data Science - R4DS](https://r4ds.hadley.nz/){target="_blank"}

Livre qui présente le [tidyverse](https://www.tidyverse.org/){target="_blank"} et déroule et présente tout au long de ses chapitres tous les outils utiles aux différentes étapes d'un projet de datascience et de modélisation. À combiner avec les ressources de [tidymodels](https://www.tidymodels.org/).

#### [Advanced-R](https://adv-r.hadley.nz/index.html){target="_blank"}

Toujours écrit par Hadley Wickham, ce livre est probablement la source détaillée la plus accessible pour comprendre en profondeur le fonctionnement du langage informatique R et les différents concepts avancés du langage.

#### [Rstudio Cheatsheets](https://posit.co/resources/cheatsheets/){target="_blank"}

Ce site recense une liste précieuse de "cheatsheet" ou anti-sèche sur des librairies de références développées par Rstudio - ou par des contributeurs externes. Probablement des documents utiles à imprimer, même au 21ème siècle.

#### [utilitR](https://book.utilitr.org/){target="_blank"}

Le projet utilitR est une documentation collaborative sur l’usage du logiciel R, née à l’Insee, destinée à tout utilisateur intéressé par la manipulation de données sans pré-requis de niveau.

### Ressources Git

#### [Vignette Usethis](https://usethis.r-lib.org/articles/git-credentials.html){target="_blank"}

Guide méthodologique rapide et efficace d'une installation de Git aux petits oignons avec [usethis](https://usethis.r-lib.org/).

#### [Happy Git and GitHub for the useR](https://happygitwithr.com/){target="_blank"}

Livre complet et détaillé de Jennifer Bryan sur l'installation et l'usage de Git sous RStudio. La partie "Useful Git patterns for real life" vous aidera au prochain fail de push/pull.

#### [Dangit, Git!](https://dangitgit.com/){target="_blank"}

Les commandes que vous auriez voulues connaitre plus tôt.
