---
title: "Evaluation"
format: typst
---

```{=typst}
#import "@preview/cheq:0.3.0": checklist
#show: checklist
```

# Évaluation du 16 avril

## Déroulé

- L'évaluation se tiendra **en salle**, pour une durée de **deux heures**.
- Toutes les ressources sont **disponibles** (cours, internet).
- Il vous est demandé de **ne pas communiquer** entre vous le temps de l'évaluation.
- La **grille d'évaluation** est disponible en bas de ce document.

## Rendu

- À la fin du temps imparti, il vous sera demandé de créer un **fichier zip** de votre projet RStudio.
- Le nom du fichier zip respectera le **format** `prenom.nom.m1ecap.zip`, **sans caractère spécial ni espace**.
    - Vérifier la conformité du nom de votre package avec `usethis:::check_package_name("prenom.nom.m1ecap")`
- Vous déposerez votre fichier zip sur le **dépôt cloud** : <https://perdu.com>.
- Attendez de recevoir la **validation** de votre dépôt avant de quitter la salle.

## Jeu de donnée

Pour rappel, le jeu de donnée utilisé pour l'évaluation doit respecter ces contraintes :

- un seul fichier
- disponible et téléchargeable en open data
- contient à minima une variable catégorielle et une variable quantitative exploitable
- format `csv`, `parquet`, `excel` ou `json`
- taille maximale de 500 ko

Pour les jeux de données bruts volumineux, il est possible de choisir une sous-partie, à condition de fournir dans votre dossier rendu **le code R utilisé pour réaliser l'ensemble des étapes d'extraction**.

Si aucun jeu de donnée n'a été sélectionné avant la date de l'évaluation, vous utiliserez le jeu de donnée **[alerte pollen](https://data.loire-atlantique.fr/explore/dataset/323266205_alerte-pollens-nantes%2540nantesmetropole/information/)** téléchargeable _[ici](https://data.loire-atlantique.fr/api/explore/v2.1/shared/datasets/323266205_alerte-pollens-nantes@nantesmetropole/exports/csv?lang=fr&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B)_.

## Grille d'évaluation

Chaque élément de la liste correctement réalisé rapporte **1pt**.

###  Création de package

```{=typst}
- [ ] Le dossier rendu est correctement nommé et contient un projet RStudio
- [ ] Le dossier rendu est un package (`isTRUE(usethis:::is_package())`)
- [ ] Le package peut être installé localement (`pak::local_install()`)
```

###  Données

```{=typst}
- [ ] Le package contient un jeu de donnée dans le sous-dossier  `data/`
- [ ] Ce jeu de donnée est disponible quand on charge le package dans un nouvelle session R
```

### Git

### Fonctions

### Développement de package
