---
title: "Exercices - 6"
format: typst
---

## Préparation

1. Créez un nouveau projet RStudio intitulé `cours_r_partie_6`, qui utilisera à la fois `git` et `renv`. Comme lors des semaines précédentes, vous créerez un projet sous GitHub correspondant pour sauvegarder vos avancées.

2. Installez et charger votre package construit lors de la session précédente depuis GitHub.

3. Utiliser le jeu de données `df_velo` préchargé dans votre package pour répondre aux questions suivantes.

## Exercice

L'objectif de cet exercice est de construire un rapport quarto paramétrable en se basant sur notre package d'analyse.

## Rapport

1. Initiez un document quarto qui s'appellera `affluence_boucle.qmd`. Les options suivantes devront être renseignées :

- _title_
- _format_ (html)
- _author_

2. Dans votre document Quarto, initiez une variable `boucle` avec la valeur de votre boucle préférée (_e.g._ `880`).

3.  En utilisant la variable `boucle`, générer le graphique d'affluence par jour de la semaine pour la boucle sélectionnée. Utiliser les fonctions `filtrer_trajet()` et `plot_distribution_semaine()`.

4. Modifiez votre code de manière à passer en *paramètres quarto* le numéro de boucle. Compilez le document quarto en modifiant les paramètres par défaut.

> Vous pourrez utiliser la fonction `quarto::quarto_render` pour compiler le document quarto. Le paramètre `execute_params` permet de spécifier les paramètres à utiliser pour la compilation d'un document. [Cette page](https://quarto.org/docs/computations/parameters.html#knitr) explique comment passer des paramètres à un document quarto R qui utiliserait `knitr` pour l'exécution des blocs de code.

*Félicitations*, vous avez généré et compilé un rapport quarto paramétrable !

5. Utiliser les paramètres du _header yaml_ quarto pour rendre votre rapport diffusable :

- Un titre, une date, un auteur
- Un sous-chapitre avec un texte de description
- Pas de code affiché
- Une table des matières
- Un thème

> Naviguer dans la [doc Quarto](https://quarto.org/docs/output-formats/html-basics.html) pour vous inspirer.

6. Ajouter le paramètre `embed-resources: true` dans vos paramètres de document Quarto. Quel est son action ?

7. Utiliser les fonctions de `renv` pour mettre à jour votre `renv.lock`

8. _Bonus_ Ajouter une fonction `get_data()` à votre package pour requêter directement les données depuis [https://data.nantesmetropole.fr/](https://data.nantesmetropole.fr/) pour une `boucle` donnée. Afin de limiter la taille de la requête, ajouter un filtre supplémentaire sur le mois sélectionné. Adapter votre Quarto et ses paramètres d'entrée pour utiliser cette fonction.
