---
title: "Exercices - 1"
format: typst
---

## Préparation

1. Vérifiez que les options globales de RStudio sont conformes aux options recommandées dans le cours.

2. Créez un projet RStudio intitulé `cours_r_partie_1`. Ce projet sera créé vide. Les options utilisation de `renv` et de `git` peuvent être ignorées.

## Exercice

Pour cet exercice, nous allons télécharger un jeu de données issu de [https://data.nantesmetropole.fr/](https://data.nantesmetropole.fr/). Le jeu de données est [disponible ici](https://data.nantesmetropole.fr/explore/dataset/244400404_comptages-velo-nantes-metropole/information/). Afin de limiter la taille du jeu de données, nous téléchargerons uniquement [les données 2025](https://data.nantesmetropole.fr/api/explore/v2.1/catalog/datasets/244400404_comptages-velo-nantes-metropole/exports/csv?lang=fr&refine=jour%3A%222025%22&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B).

1. Téléchargez le jeu de donnée dans le projet RStudio. Créez un script `.R` ou un fichier quarto intitulé `exercice`.

2. Lisez le fichier téléchargé. Le résultat sera affecté à l'objet de nom `data_ex`. Combien de colonnes comprend le jeu de données ? Quels sont les noms et la nature des colonnes ? Combien de lignes contient le `data.frame` ?

3. Combien y a-t-il de boucles référencées ?

4. Combien y a-t-il de jours référencés ?

5. Combien y a-t-il de comptage avec une forte probabilité d'anomalie ?

6. Quelle boucle compte le plus de trajet ? Quelle boucle en compte le moins ?

7. Quel est le top 10 des jours possédant le plus de trajet ?

8. Quel est le nombre de trajets pour chaque période de vacances ?

9. Quelle est la proportion de trajet par jour de la semaine ? Quelle est votre analyse ?

10. Représentez et visualisez la distribution du nombre de trajets par jour de la semaine.

11. Quel est le jour de la semaine avec la moyenne de trajet la plus haute ? Obtient-on le même résultat si on réalise le calcul séparément sur chaque période de vacances ?

### Aide pour l'exercice

- Utilisez la fonction d'aide `?` pour déterminer les bons paramètres de lecture.
- Si vous rencontrez des erreurs SSL lors du téléchargement, lancer la commande `options(download.file.method = "curl", download.file.extra = "-k -L")`
- La lecture d'un fichier `csv` peut se faire en `base R` avec `read.delim` ou avec `readr` et la fonction `read_delim`.
- Les fonctions `group_by` et `summarise` de `dplyr` peuvent vous aider à calculer des sommes et des moyennes.
- La carte des boucles et disponible [ici](https://data.nantesmetropole.fr/explore/embed/dataset/244400404_comptages-velo-nantes-metropole-boucles-comptage/custom/?disjunctive.libelle&disjunctive.boucle_num&sort=boucle_num).
